### ISSUE TITLE
Implement the GitHub authentication screens

### ISSUE THREAD

**Issue by lukasz-starosta** [karczewskiPiotr/vnlab-tool#11]
## Description
Refer to the prototype and the flow to know how to deal with it. Make it a simple GitHub login. An embedded version of the login is better than a popup (like when you're not authenticated to git and try to push for example). Make sure to show the errors and loading states.

## Correct issue checklist:
- [x] I have added a detailed description
- [x] I have specified the environment
- [x] I have assigned a Team label (front-end / node / git / design / gatsby)
- [x] I have assigned a Description label (enhancement / bug / etc.)
- [x] I have assigned a Project

**Comment by szymonrucinski** [comment]
![login](https://user-images.githubusercontent.com/44577190/100937184-e98d1780-34f2-11eb-8e9c-d3f863f0fef9.png)
