### ISSUE TITLE
Figure out how to tackle state management

### ISSUE THREAD

**Issue by lukasz-starosta** [karczewskiPiotr/vnlab-tool#4]
Considerations
* Are there alternatives to Redux?
    * Our own approach with React Context API?
* If Redux do we use the toolkit or not?

**Comment by lukasz-starosta** [comment]
I think we should use [electron-redux](https://github.com/klarna/electron-redux)

**Comment by karczewskiPiotr** [comment]
I'd suggest coupling it with [redux-toolkit](https://redux-toolkit.js.org/introduction/quick-start) to minimize the crazy boilerplate shenanigans that using bare Redux ends up creating. 💁 

It would remove the need to write immutable update logic and simplify store configuration as well.

**Comment by lukasz-starosta** [comment]
Sure, let's try

**Comment by 217853** [comment]
I vote for electron-redux.
