### ISSUE TITLE
Figure out how to tackle navigation

### ISSUE THREAD

**Issue by lukasz-starosta** [karczewskiPiotr/vnlab-tool#5]
Considerations
* If using `react-router` is `MemoryRouter` the best option?
* Are there any valid alternatives to `react-router`?

**Comment by lukasz-starosta** [comment]
I think we do not need to use an external router, because Electron has its own routing 
https://www.electronjs.org/docs/api/web-contents#instance-methods

**Comment by karczewskiPiotr** [comment]
> I think we do not need to use an external router, because Electron has its own routing
> https://www.electronjs.org/docs/api/web-contents#instance-methods

Haven't looked into this to much but the following things poped into my head on initial lack of Google results:
1. Since we are moving onto a UI based on containers that change content, will this approach allow us to write conditional rendering of components in an approachable way?
2. Won't this approach enforce the need to rerender the whole UI on address change?
3. Apart from the docs there seems to be little material on how to use it and best practices.

**Comment by lukasz-starosta** [comment]
Yes, I forgot that using Electron does not mean using React. We may then use `react-router` but with a different `Router` than usually on the web. See:
https://stackoverflow.com/questions/36505404/how-to-use-react-router-with-electron

**Comment by 217853** [comment]
I found building app in electron using react/angular framweork is easier than using only DOM in electron. So we have to pick one of those frameworks imo anyway.

**Comment by 217853** [comment]
> * If using `react-router` is `MemoryRouter` the best option?

`MemoryRouter ` is good option when working in React as far as i know

**Comment by karczewskiPiotr** [comment]
> Yes, I forgot that using Electron does not mean using React. We may then use `react-router` but with a different `Router` than usually on the web. See:
> https://stackoverflow.com/questions/36505404/how-to-use-react-router-with-electron

Exactly, the question is which one to go for. Both `HashRouter` and `MemoryRouter` would work for the basics of what we need but there may be some quirks to consider in both cases.

The other thing is that react-router ream [discourages](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md) use of HashRouter but that could be in case of normal usage in the browser.
> As this technique is only intended to support legacy browsers, we encourage you to configure your server to work with <BrowserHistory> instead.

[Here](https://learnwithparam.com/blog/different-types-of-router-in-react-router/)'s a comparison of all routers for reference.

We could potentially start of with `MemoryRouter` and transition to `HashRouter` if we encounter any problems with GitHub authentication in separate browser.

**Comment by karczewskiPiotr** [comment]
> I found building app in electron using react/angular framweork is easier than using only DOM in electron. So we have to pick one of those frameworks imo anyway.

Already settled for using React in this project. 👍

**Comment by 217853** [comment]
> We could potentially start of with `MemoryRouter` and transition to `HashRouter` if we encounter any problems with GitHub authentication in separate browser.

Good idea. Depends how the github login process is embedded (or separated) in our app. Its supposed to be as a separate, normal github page login yes?

**Comment by karczewskiPiotr** [comment]
Probably the most straightforward and credible way ([from available](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/about-authentication-to-github)) for the user to open it in the web browser or a separate chromium instance.

The thing with [GitHub OAuth](https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#web-application-flow) authentication is that it uses a redirect uri with code that can be exchanged for a token so the team has to see how this functionality can be implemented in Electron environment and what the redirect uri would be of we use `MemoryRouter`.
